### ISSUE TITLE
Logic for responding on unknown Auth Ctrl value

### ISSUE THREAD

**Issue by quite** [psanford/ctapkey#1]
There is a check that the Auth Ctrl value is known both here in the decoding: https://github.com/psanford/ctapkey/blob/main/u2f/u2f.go#L79 and here in handleAuthenticate: https://github.com/psanford/ctapkey/blob/main/ctapkey.go#L130

The latter will never happen, because decoding the auth req would fail. The former check does not do any WriteResponse, but the latter would. Wondering if this is fine -- not responding if the Auth Ctrl is unknown. Because that's how the code currently behaves. If so, the check in handleAuthenticate should probably just be removed.

Perhaps I have not gotten the overall gist of the U2F protocol, and a response is not really expected -- it is rather up to the FIDO client to do retries/timeouts. It does feel like that from reading your implementation, as you don't do any WriteResponse on several occasions of errors. Because, yeah, there would not even be any really suitable response code (there are not many of them either).

**Comment by psanford** [comment]
The check for if the type is known or not in the two sections of the code is done for robustness and future proofing.

Each function knows what it is able to process or not independently of the other. This means that if additional Ctrl states were added to `u2f.DecodeAuthenticatorRequest` it wouldn't break the assumptions of `ctapkey.handleAuthenticate`.

If this were written in a language like rust we could enforce this safety at the language layer by using a proper enum and an enforced check that we handle all values of that enum. But we don't have that in Go so we write a bit of extra code to gain that safety.

In terms of when we send a response, U2F is a polling protocol that has short timeouts and retries baked into it. The browser isn't expecting a response until the authenticator has something interesting to report. 

But also, we are under no obligation to respond to requests we don't understand or that break the state machine. If something is broken a log message in the authenticator application will be able to provide more useful information to the user than a generic error back to the browser or the relying party.

**Comment by quite** [comment]
Thanks for the clarifications! this made sense to me: "we are under no obligation to respond to requests we don't understand or that break the state machine. "  Closing this.
